name: "build and push docker image"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: set up qemu
        uses: docker/setup-qemu-action@v2
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: cache docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: prepare current date arg
        env:
          tz: "asia/tokyo"
        run: echo "current_datetime=$(date +'%y%m%d%h%m%s')" >> $github_env

      - name: login to github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}

      - name: prepare cache
        run: mkdir -p /tmp/.buildx-cache || true
      - name: build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./dockerfile
          build-args: |
            env_file=.env.build
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/potato_leaves:${{ env.current_datetime }}
            ghcr.io/${{ github.repository_owner }}/potato_leaves:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          ulimit: nofile=1024000:1024000

      - name: move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
